# -*- coding: utf-8 -*-
txts = ['Plazo de pago',
'Zona',
'F. ACCIÓN SALIENTE',
'DESCONECTARSE',
'Responsable SCO Applus',
'Fecha',
'Fecha próxima acción',
'departamento / proyecto',
'N. descriptivo',
'CARGA',
'CÓD. CL',
'INGLÉS',
'Código cliente',
'Descripción proyecto',
'Cód. proyecto',
'Horario contacto',
'Cargar facturas',
'Nombre',
'Aceptar',
'Código',
'EXPORTAR RESULTADO',
'Resultado acción saliente',
'Carga de facturas',
'TEXTO ACCIÓN',
'Teléfono',
'CIF/NIF',
'ESPAÑOL',
'A12345678',
'Fecha vencimiento',
'Texto factura',
'COBRA, INSTAL Y SERV. S.A',
'Nueva acción sobre la factura',
'Nº FACTURA',
'F. PRÓXIMA ACCIÓN',
'División',
'CARGAR FACTURAS',
'F. VENCIMIENTO',
'Referencia',
'IMPORTE',
'RESULTADO ACCIÓN',
'Facturas',
'Nombre jefe de proyecto',
'Usuario',
'Acción saliente',
'Identificador',
'Falta documentación de la factura. Se pide confirmación',
'DEPARTAMENTO',
'Próxima acción',
'Falta documentación de la factura',
'Departamento:',
'Consultar facturas',
'Llamar tardes',
'ACTUALIZAR',
'Última acción sobre la factura',
'PRÓXIMA ACCIÓN',
'CREAR ACCIÓN',
'Comentarios',
'Texto acción',
'Acciones sobre la factura',
'NOMBRE CLIENTE',
'ADJUNTOS',
'VER DETALLE',
'BUIET ELECTRICO NO',
'E-mail',
'Fecha acción salientes',
'Cliente / departamento / proyecto',
'Ubicación',
'LIMPIAR',
'Contraseña',
'Fecha acción saliente',
'Día de pago',
'BUSCAR',
'Nº Jefe',
'Llamada saliente',
'ACCIÓN SALIENTE',
'login',
'RECLAMACIÓN',
'Datos de la \ factura',
'Filtro de / búsqueda',
'Importe']